name: Test Akash Composite Action
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Akash On Github Actions
        uses: dmikey/akash-on-gh-actions@v1.0.89
        with:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
