name: Test Akash Dynamic SDL Action
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Akash on Github Actions Setup
        uses: ovrclk/akash-ghaction-templated-sdl@v4-dev
        env:
          VERSION_TEST: 1234abcd
      - run: -|
          cat deploy.yaml
