name: Update Deployment on Akash
on:
  workflow_dispatch:

jobs:
  publish-on-akash:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Blockless Action Setup
        uses: txlabs/github-action-blockless-setup
