on: [push]

jobs:
  akash_deploy:
    runs-on: ubuntu-latest
    name: a job to deploy on akash network
    steps:
      - name: Check Akash Version
        uses: dmikey/akash-on-gh-actions@v1.0.75
        with:
          secrets: |
            AKASH_WALLET_KEY=${{ secrets.AKASH_WALLET_KEY }}
            AKASH_WALLET_KEY_PASSWORD=${{ secrets.AKASH_WALLET_KEY_PASSWORD }}
