on: [push]

env:
  AKASH_HOME: /home/runner/.akash
  AKASH_NODE: tcp://rpc0.mainnet.akash.network:26657
  AKASH_GAS: auto
  AKASH_GAS_ADJUSTMENT: 1.15
  AKASH_GAS_PRICES: 0.025uakt
  AKASH_SIGN_MODE: amino-json
  AKASH_CHAIN_ID: akashnet-2
  AKASH_FROM: AKASH_GROWTH_TEAM
  AKASH_KEYRING_BACKEND: test
jobs:
  publish-on-akash:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: installing toolset
        run: sudo apt install wget curl jq
      - name: install akash binaries
        run: |-
          wget $(curl -H "Authorization: token ${{secrets.GITHUB_TOKEN}}" -s https://api.github.com/repos/ovrclk/akash/releases/latest | jq -r ".assets[] | select(.name | test(\"linux_amd64.deb\")) | .browser_download_url") -O akash.deb
          sudo dpkg -i akash.deb
          wget $(curl -H "Authorization: token ${{secrets.GITHUB_TOKEN}}" -s https://api.github.com/repos/ovrclk/e2e-production/releases/latest | jq -r ".assets[] | select(.name | test(\"linux_amd64.deb\")) | .browser_download_url") -O e2e.deb
          sudo dpkg -i e2e.deb
      - name: import key
        run: |-
          echo "${{secrets.AKASH_WALLET_KEY}}" > key.key
          echo "${{secrets.AKASH_WALLET_KEY_PASSWORD}}" | akash keys import ${{env.AKASH_FROM}} key.key
          rm key.key
      - name: import certificate
        run: echo "${{secrets.DEPLOY_CERT}}" > ${{env.AKASH_HOME}}/$(akash keys show ${{env.AKASH_FROM}} --output=json | jq -r ".address").pem
      - name: get last active deployments
        run: |-
          export AKASH_DSEQ=$(akash query deployment list --owner "$(akash keys show "AKASH_GROWTH_TEAM" -a)" --state active -o json --limit 1 | jq -r ".deployments[0].deployment.deployment_id.dseq")
          echo "AKASH_DSEQ=$AKASH_DSEQ" >> $GITHUB_ENV
      - name: update deployment
        run: |-
          akash tx deployment update deploy.yml --dseq $AKASH_DSEQ --from ${{env.AKASH_FROM}} --chain-id $AKASH_CHAIN_ID --node $AKASH_NODE --fees=5000uakt -y
      - name: query deployment
        run: |-
          akash provider lease-status --node $AKASH_NODE --dseq ${{env.AKASH_DSEQ}} --from ${{env.AKASH_FROM}} --provider $AKASH_PROVIDER
